services:
  db:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    container_name: transcendence_db
    volumes:
      - ./data:/usr/src/app/data
      - node_modules_db:/usr/src/app/node_modules
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: transcendence_backend
    working_dir: /usr/src/app
    environment:
      - DB_URL=https://transcendence_db:3000
      - ALLOW_SELF_SIGNED=true
    volumes:
      - ./backend:/usr/src/app
      - node_modules_be:/usr/src/app/node_modules
      - ./data:/usr/src/app/data
      - ./backend:/usr/src/app
    ports:
      - "8080:8080"
      - "8082:8082"
      - "8083:8083"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: transcendence_frontend
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
      - node_modules_fe:/usr/src/app/node_modules
    ports:
      - "5173:5173"
      - "8081:8081"
    environment:
      - HOST=0.0.0.0

volumes:
  node_modules_fe:
  node_modules_be:
  node_modules_db:
