services:
  db:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    container_name: transcendence_db
    volumes:
      - ./data:/usr/src/app/data
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: transcendence_backend
    working_dir: /usr/src/app
    environment:
      - DB_URL=https://transcendence_db:3000
      - ALLOW_SELF_SIGNED=true
    volumes:
      - ./data:/usr/src/app/data
    ports:
      - "8080:8080"
      - "8082:8082"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: transcendence_frontend
    working_dir: /usr/src/app
    ports:
      - "8081:8081"
